<?php

namespace AppBundle\Repository;

/**
 * ColeresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColeresRepository extends \Doctrine\ORM\EntityRepository
{
}
