security:
    encoders:
        AppBundle\Entity\User: bcrypt
    providers:
        user:
            entity:
                class: AppBundle\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            logout_on_user_change: true
            provider: user
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: dashboard
            logout:
                path: logout
                target: login

    #access_control:
        #- { path: ^/homepage, roles: "ROLE_USER" }
        #- { path: ^/admin, roles: "ROLE_ADMIN" }